FROM python:3.10-slim

ARG SERVICE

COPY ./$SERVICE /code/$SERVICE
COPY ./$GOOGLE_APPLICATION_CREDENTIALS /$GOOGLE_APPLICATION_CREDENTIALS

WORKDIR /code/$SERVICE
ENV PYTHONPATH=/code/$SERVICE

RUN pip install --user -r /code/$SERVICE/requirements.txt

ENTRYPOINT ["python"]
