version: '3'

services:
  twitter:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-twitter
    environment:
      API_KEY: ${API_KEY}
      API_KEY_SECRET: ${API_KEY_SECRET}
      BEARER_TOKEN: ${BEARER_TOKEN}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
    volumes:
      - ./:/code