version: '3'

services:
  twitter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_KEY: ${API_KEY}
      API_KEY_SECRET: ${API_KEY_SECRET}
      BEARER_TOKEN: ${BEARER_TOKEN}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./:/code

  bigquery:
    build:
      context: .
      dockerfile: bigquery/Dockerfile
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./:/code
