version: '3'

services:
  extract:
    image: tweet-graphs-extract
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
      args:
        SERVICE: extract
    extends:
      file: common.yaml
      service: elt
    environment:
      API_KEY: ${API_KEY}
      API_KEY_SECRET: ${API_KEY_SECRET}
      BEARER_TOKEN: ${BEARER_TOKEN}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}


  load:
    image: tweet-graphs-load
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
      args:
        SERVICE: load
    extends:
      file: common.yaml
      service: elt
    environment:
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
      BIGQUERY_DATASET: ${BIGQUERY_DATASET}

  # transform:
  #   image: tweet-graphs-transform
  #   build:
  #     context: .
  #     dockerfile: ./docker/dbt/Dockerfile
  #     args:
  #       SERVICE: transform
  #   volumes:
  #     - ./:/code